### ISSUE TITLE
Request for complete details about recent DDoS attach.

### ISSUE THREAD

**Issue by hvredevoort** [CPChain/chain#102]
Please provide complete details about the recent DDoS attach on the RNodes which started on March 1 at 04:02:44. What happened? Where did it come from? What effects did it have on the chain? How will nodes be punished for involuntary creating impeached blocks? Did the team nodes suffer? Did the validators suffer? What measures are taken against DDoS? How was this solved?
Any other info is very welcome. 
Thanks, Hans

![image](https://user-images.githubusercontent.com/6986026/75774466-a85cb100-5d82-11ea-86cd-f8921e6f06dd.png)

![image](https://user-images.githubusercontent.com/6986026/75774404-85320180-5d82-11ea-8cd3-2ba8bbb2671a.png)

**Comment by CPC-Yao** [comment]
What happened? 
So many impeach blocks are because the system misjudged the DDoS attack and blocked external traffic.  

Where did it come from? 
The system misjudged because the monitoring node disk is full.

What effects did it have on the chain? 
External proposers cannot connect to validators, and it caused them to continue to produce impeach blocks.

How will nodes be punished for involuntary creating impeached blocks? 
The punishment is the same, regardless of whether they are voluntary. However, the reduced RPT will return to normal after 10,000 blocks.

Did the team nodes suffer? 
No, system only blocks external traffic. Team nodes will continue to ensure the chain runs.

Did the validators suffer?
No.

What measures are taken against DDoS? How was this solved?
Once the system detects a DDoS attack, it will block external traffic.

How was this solved?
We upgraded the monitoring nodes and added alarm and automatic restart mechanisms. In addition, we inspect the machines manually every week.

**Comment by hvredevoort** [comment]
Thank you for these excellent answers. Much appreciated!
Hans
