### ISSUE TITLE
Several impeached blocks 0.2.7

### ISSUE THREAD

**Issue by L0ut** [CPChain/chain#27]
**Where does the bug occur?**
visible on the explorer but everything seems normal on the command prompt

**What is your wallet address and your balance?**
0x295226d148533706caee6f94917b4134f53c1180
366000cpc

**Describe the bug**
impeached blocks on visible on the explorer 

**Expected behavior**
No impeached blocks
![impeached blocks](https://user-images.githubusercontent.com/50440757/57631090-1f7c4b00-759f-11e9-8e3b-1b0d59c0c095.jpg)

** Configuration (please complete the following information):**
 - OS: windows 2016 recommended specs
 - cpchain version 0.2.7

**Comment by alex031029** [comment]
Impeaching block may due to several reasons, including ones related to your server, like bandwidth and CPU consumption. At the current stage, we assume it's independent case for the lack of other evidences. 

If you or other user encounter similar situation again, we will raise the priority of this issue.

**Comment by alex031029** [comment]
#18  and #33 are similar issues as this one. Here I merge these three issues.
