### ISSUE TITLE
Get into committee without sealing blocks 

### ISSUE THREAD

**Issue by alex031029** [CPChain/chain#36]
**Where does the bug occur?**
chain

**What is your wallet address and your balance?**
If it is too private to answer, you can skip it. 

**Describe the bug**
This bug is highly related to #26 . 
I raise this issue on behalf of @brammb who post his error message in #30 .

INFO[05-17|08:29:36.328] campaign for proposer committee eleTerm=11689
INFO[05-17|08:29:36.328] Start campaign for dpor proposers committee
INFO[05-17|08:29:36.445] found nonce block hash=0x7262008e5eeab726eafa0dabbe327235b7133e083edd7e6b28a5d95ae0ee0327 difficulty=12 nonce=3848 sender=0x116143Ba590b7a7dc75f276243Da0A4bfC0Ae373 timeCost(s)=0.0759948
INFO[05-17|08:29:37.574] found nonce block hash=0x7262008e5eeab726eafa0dabbe327235b7133e083edd7e6b28a5d95ae0ee0327 difficulty=6 nonce=53 sender=0x116143Ba590b7a7dc75f276243Da0A4bfC0Ae373 timeCost(s)=1.2049968
INFO[05-17|08:29:38.456] Submitted transaction fullhash=0x4e2b587dac7404ad0937e27fa4890b57760cbf646d6eb9392b01d49e0253d62f recipient=0xb8A07aE42E2902C41336A301C22b6e849eDd4F8B
INFO[05-17|08:29:38.457] Claimed for campaign CpuBlockNumber=420804 CpuPowResult=3848 MemBlockNumber=420804 MemPowResult=53 NumberOfCampaignTerms=3
INFO[05-17|08:29:45.154] Synchronization Started local height=420805 peer=f38cb2bec4472c34 peer.Head=0x9a2f5a58b913f115b21b23fa64671fda781fcc6cf2de48bae9feac76f159a512 peer.height=420806
INFO[05-17|08:29:45.192] Imported new chain segment blocks=1 cache="11.13 kB" elapsed=26.004ms hash=0x9a2f5a58b913f115b21b23fa64671fda781fcc6cf2de48bae9feac76f159a512 mgas=0.147 mgasps=5.652824297146285 number=420806 txCounterAfterStartup=256896 txs=7
INFO[05-17|08:29:57.540] Synchronization Started local height=420806 peer=f38cb2bec4472c34 peer.Head=0x1f38f4f21370ac7360bdb5c66cabf892b4eb8138952eba13f832c074ff274e43 peer.height=420807
INFO[05-17|08:29:57.616] Synchronization Started local height=420806 peer=853629f5745dadaa peer.Head=0x1f38f4f21370ac7360bdb5c66cabf892b4eb8138952eba13f832c074ff274e43 peer.height=420807
INFO[05-17|08:29:57.617] Synchronization Started local height=420806 peer=0a6fde7294df61b6 peer.Head=0x1f38f4f21370ac7360bdb5c66cabf892b4eb8138952eba13f832c074ff274e43 peer.height=420807
INFO[05-17|08:29:57.624] Synchronization Started local height=420806 peer=903cf555890daef5 peer.Head=0x1f38f4f21370ac7360bdb5c66cabf892b4eb8138952eba13f832c074ff274e43 peer.height=420807
INFO[05-17|08:29:57.633] Synchronization Started local height=420806 peer=44eb2b4a478a9d14 peer.Head=0x1f38f4f21370ac7360bdb5c66cabf892b4eb8138952eba13f832c074ff274e43 peer.height=420807
INFO[05-17|08:29:57.652] Synchronization Started local height=420806 peer=6cb080d2098cf91e peer.Head=0x1f38f4f21370ac7360bdb5c66cabf892b4eb8138952eba13f832c074ff274e43 peer.height=420807
INFO[05-17|08:29:57.675] Synchronization Started local height=420806 peer=8aa2c51240fd7b62 peer.Head=0x1f38f4f21370ac7360bdb5c66cabf892b4eb8138952eba13f832c074ff274e43 peer.height=420807
INFO[05-17|08:29:57.730] Synchronization Started local height=420806 peer=f01e7ad4e63a063c peer.Head=0x1f38f4f21370ac7360bdb5c66cabf892b4eb8138952eba13f832c074ff274e43 peer.height=420807
INFO[05-17|08:29:57.887] Synchronization Started local height=420806 peer=f01e7ad4e63a063c peer.Head=0x1f38f4f21370ac7360bdb5c66cabf892b4eb8138952eba13f832c074ff274e43 peer.height=420807
INFO[05-17|08:29:58.210] Imported new chain segment blocks=1 cache="333.83 kB" elapsed=659.007ms hash=0x1f38f4f21370ac7360bdb5c66cabf892b4eb8138952eba13f832c074ff274e43 mgas=6.52509 mgasps=9.901388087178358 number=420807 txCounterAfterStartup=256934 txs=38

I quote his comments here 

> I can get on the committee and claim for campaign, but I never seal any blocks anymore.
> From update to 2.8 I have sealed 6 blocks.

**Comment by brammb** [comment]
What is your wallet address and your balance?
0x116143Ba590b7a7dc75f276243Da0A4bfC0Ae373 - Balance: 425658.569030658 CPC

Hardware:
VPS - 6vpcu's - 8gb RAM - 300gb ssd - Windows Server 2019

Bugs:
9 blocks secured since update to 2.8, 3 days ago.

Bug1: Proposed blocks don't get sealed without error or warning.

INFO[05-17|08:29:36.328] campaign for proposer committee eleTerm=11689
INFO[05-17|08:29:36.328] Start campaign for dpor proposers committee
INFO[05-17|08:29:36.445] found nonce block hash=0x7262008e5eeab726eafa0dabbe327235b7133e083edd7e6b28a5d95ae0ee0327 difficulty=12 nonce=3848 sender=0x116143Ba590b7a7dc75f276243Da0A4bfC0Ae373 timeCost(s)=0.0759948
INFO[05-17|08:29:37.574] found nonce block hash=0x7262008e5eeab726eafa0dabbe327235b7133e083edd7e6b28a5d95ae0ee0327 difficulty=6 nonce=53 sender=0x116143Ba590b7a7dc75f276243Da0A4bfC0Ae373 timeCost(s)=1.2049968
INFO[05-17|08:29:38.456] Submitted transaction fullhash=0x4e2b587dac7404ad0937e27fa4890b57760cbf646d6eb9392b01d49e0253d62f recipient=0xb8A07aE42E2902C41336A301C22b6e849eDd4F8B
INFO[05-17|08:29:38.457] Claimed for campaign CpuBlockNumber=420804 CpuPowResult=3848 MemBlockNumber=420804 MemPowResult=53 NumberOfCampaignTerms=3
INFO[05-17|08:29:45.154] Synchronization Started local height=420805 peer=f38cb2bec4472c34 peer.Head=0x9a2f5a58b913f115b21b23fa64671fda781fcc6cf2de48bae9feac76f159a512 peer.height=420806
INFO[05-17|08:29:45.192] Imported new chain segment blocks=1 cache="11.13 kB" elapsed=26.004ms hash=0x9a2f5a58b913f115b21b23fa64671fda781fcc6cf2de48bae9feac76f159a512 mgas=0.147 mgasps=5.652824297146285 number=420806 txCounterAfterStartup=256896 txs=7
INFO[05-17|08:29:57.540] Synchronization Started local height=420806 peer=f38cb2bec4472c34 peer.Head=0x1f38f4f21370ac7360bdb5c66cabf892b4eb8138952eba13f832c074ff274e43 peer.height=420807


Bug 2: error="failed to estimate gas needed: gas required exceeds allowance or always failing transaction"

INFO[05-17|18:23:16.128] campaign for proposer committee               eleTerm=11782
INFO[05-17|18:23:16.128] Start campaign for dpor proposers committee
INFO[05-17|18:23:16.297] found nonce                                   block hash=0xe508540fdc6494c51330cb9fc2546e03ab4beb5cb00c00f7ff498a289282afc7 difficulty=12 nonce=8247 sender=0x116143Ba590b7a7dc75f276243Da0A4bfC0Ae373 timeCost(s)=0.1449989
INFO[05-17|18:23:18.239] found nonce                                   block hash=0xe508540fdc6494c51330cb9fc2546e03ab4beb5cb00c00f7ff498a289282afc7 difficulty=6 nonce=97 sender=0x116143Ba590b7a7dc75f276243Da0A4bfC0Ae373 timeCost(s)=2.086996
WARN[05-17|18:23:18.949] Error in claiming campaign                    error="failed to estimate gas needed: gas required exceeds allowance or always failing transaction"
INFO[05-17|18:23:35.049] Synchronization Started

**Comment by brammb** [comment]
Getting blocks again, 36 in the last 24h.

Still get bug 2.

INFO[05-19|14:34:26.113] campaign for proposer committee               eleTerm=12190
INFO[05-19|14:34:26.113] Start campaign for dpor proposers committee
INFO[05-19|14:34:26.211] found nonce                                   block hash=0x9caf9d8da9adfcc483ffd28a73c4530b4998f60935642ee29ef4d7e22d126d04 difficulty=12 nonce=4038 sender=0x116143Ba590b7a7dc75f276243Da0A4bfC0Ae373 timeCost(s)=0.0729961
INFO[05-19|14:34:27.437] found nonce                                   block hash=0x9caf9d8da9adfcc483ffd28a73c4530b4998f60935642ee29ef4d7e22d126d04 difficulty=6 nonce=63 sender=0x116143Ba590b7a7dc75f276243Da0A4bfC0Ae373 timeCost(s)=1.2990059999999999
WARN[05-19|14:34:28.130] Error in claiming campaign                    error="failed to estimate gas needed: gas required exceeds allowance or always failing transaction"
INFO[05-19|14:34:45.022] Synchronization Started

**Comment by alex031029** [comment]
Thanks for your information. We are investigating it.
