### ISSUE TITLE
Critical: Proposer for a better Election Prozess

### ISSUE THREAD

**Issue by Mateus224** [CPChain/chain#37]
I was reading on Bitbucket : https://bitbucket.org/cpchain/chain/pull-requests/657/chain-1063-docs-refinement-with-white/diff 

and it looks that we get hard divided into 2 groups (in the 0.2.9 version). That could be better then the last version where not everybody was selected but such a hard division is not a real fair selection... and could still not solve completely the problem ! Because if you make it with a hard division it could again happens that a few people e.g. from the low reputation pool will be not selected if the pool will be much bigger (hundrets of low RPT Nodes in the mainnet).  Then you should again divided it...? I think a continuous solution would be better then a discreet.! If i observe it right our RPT starts after we were selected again by nearly 0. How fast the RPT is growing depends on the factors like how many CPC we are owning and other stuff. I think a more fair division we could reach not with a hard division into two groups but with (maybe) the Softmax-Function over all Nodes (where the Nodes are the Categories (K) in this function). The RPT is growing  over time with a Sigmoid function until we were selected and a weighted random  selection from the results of the Softmax-Function gives the result if the Node will be selected or not. 

So why a complex Softmax-function and not like now a normal linear function which just calculate the selection based on the Reputation. Because now we have the problem that the Nodes which has a high RPT are growing the whole time, every node linear with a different gradient, what leads to that, that the reputation from the lower RPT nodes are in relation to the high RPT Node are getting smaller even they were waiting very long. And the high RPT overtakes everytime the small RPT Nodes ( if the calculations of RPT of the nodes are in relation to each other). My proposal is to make a nonlinear Function, a Sigmoid function. Where the nodes after a selection are growing first slower then very fast and on the end they stop growing. So that even if we have a high RPT Node it will not get a higher RPT as a loooong waiting Low RPT Node. They will be nearly equal, so that both have the same chance.

And how fast somebody can be elected depends on the weights of the Sigmoid function. Maybe you can calculate then the Reputation in % to other nodes with the Softmax function and choose them then random .

So one more time: 
If you have a high reputation you can always overtake the other because how i observe it, your reputation is calculated based on the rest of the nodes. So your reputation can go down if the reputation of the rest of the Nodes go up (in %). 
Then higher my RPT is, then faster i growth, then faster i growth then faster i get more % in reputation and the smaller are losing RPT % then. This is the Issue the RPT % should never go down. But that happens because you are trying to solve a nonlinear problem with a linear function and the higher your RPT is then you get Exponential selected. 
This can be solved with a nonlinear function, then the small RPT Nodes dont get down in % but they growth just slower. So that we dont need make a discrete election process. On the end every smaller RPT Nodes get selected after more time and the Higher RPT gets selected more frequently like it should be.

Softmax-Function:
j=Node
K=Number of Nodes

![photo_2019-05-17_19-05-22](https://user-images.githubusercontent.com/24302453/57944296-d433a680-78d6-11e9-9393-a55bfff158cc.jpg)

**Comment by alex031029** [comment]
I usually don't reply on issue page when I am out of office. But I am glad you reviewed our pull requests, and particularly commented on my pull request. 

If you have reviewed the code in `elect.go`, you may find the current implementation is somewhat similar to your proposal (but the code contains bugs. Thus, the election process does not work as we supposed). In `elect.go`, we map all RPT values to a logarithm function log2(x), in order to amplify the chance of nodes with high RPT, while retain some seats for the rest nodes. Logarithm function works pretty like sigmoid or softmax function, monotonic increasing while its 2nd derivative is negative. 

The major reason for designing a logarithm function is that we are afraid of a long-tail distribution of all RPT values. But one fundamental requirement has changed, which is that we won't calculate RPT for all RNodes. Instead, only earliest 100 RNodes getting their transactions on the chain can claim campaign. 

The reason is that RPT calculation was too time-consuming. It was simply prohibitively slow if when we set hundreds of dummy nodes calculating RPT for each other. 

I concur that softmax function is pretty decent. It is more succinct and intuitive compared to logarithm function. Discussion is always welcome and I am still considering this election model. Feel free to post any idea here, although it is weekend I may not reply on time :)

**Comment by Mateus224** [comment]
Nice that you give such a detailed answer. It would be much easier if you would have written this in pseudo code or in math what you are going to do exactly, so that we can improve that. I will write some points why i think that log2(x) is good but sigmoid / softmax could be better. 
If you will calculate the election based on log2(x) it will still prefer high RPT Nodes  disproportionately stronger then the Nodes with the lower RPT and could teoretically leads to the problem i described at the first comment (Of cours not so strong). Why? Because log2(x) dont converges against a number so you dont know the upper bounds. If we dont know the upper bounds the function could reduce from a smaller node its RPT in "%" if the higher RPT increases. Like i wrote in the comment before :
--
Then higher my RPT is, then faster i grow. Then faster i grow , then faster i get more % in reputation.And the small RPT Nodes are losing RPT in % (comapred to the other and on RPT in % we are doing the selection). I think that is an issue, the RPT in % from every Node should NEVER go down but always increasing in % to the rest. So that you everytime you will get NOT elected you RPT in % is increasing that you get higher chances to get elected by the next time and never go down. The only reason to go down should be after the node was elected.
--
You could use a PT1 [ U(1-e^-(t/T))] which converges against U or easier the  Sigmoid function which converges against 1 and that is a second benefit of sigmoid that we could then just use the softmax function to get the probebilities directly for the selection. 
And an other reason why I prefere the solution of a Sigmoid against a log2(x) [or 1-e^(-t/T)] is, that after a selection the RPT of the nodes increases very slow at the beginning when you use the Sigmoid function [I think this could be important]. WHY? Imagine there is somebody who want destroy the Network. He owns 3high reputation Nodes so he will maybe get elected 3time in row. He will do 9 Blocks and after the last node has created the last block, his first node which created the first block could recover his reputation in this time because of the faster growing log2(x) in % at the beginning (then Sigmoid) and could create again 3 Blocks. So many Blocks creating in row from one person is very dangerous for the Blockchain, he could impeach the network. I think a Sigmoid function reduces here the risc that one person can do many Blocks in row, because it grows very slow at the beginning and very fast in the middle and it converges against 1 what makes the calculations muuuuch easier. 


PS: I hope you understand what i m trying to write but its already to late for me to do math and i know i have to improve my english :D 
Maybe i will take a look into the election code when i will finde some time, but it would be easier to have some pseudo code.

**Comment by sysadmin42** [comment]
I like the idea of a RPT % that cannot decrease, only after being elected.
A smaller Rnode holder can then rest assured that his chances will increase, so that his patience will pay off.
If not, holder of smaller nodes will get frustrated and give up, what would be bad for the network, that should want to have as many nodes (if enough physically equipped of course) as possible.
If you math experts can come up with a proper constant to be applied to the sigmoid to make sure the benefits for a node are more or less proportional to its deposit, I'd be very happy.

**Comment by Mateus224** [comment]
Okay it was little bit late yesterday and in one point i m not sure if my statemant is 100% correct: If the RPT in % will never decrease with softmax, but i think that could be right. But even it wouldnt, it would do less decrease the REP in % then log2(x). This statement should be mathematically proven^^

An other point why Softmax (Sigmoid) is better. Lets assume we have 10 RNodes. This 10 Rnodes are mapped on the log2(x) function. Now we add a new heavy RNode which is mapped to the log2 function. But we know that the log2 function dont effect small numbers so strong like large. So Automatically in % the (maybe) long waiting nodes get a strong decrease of RPT in % because of the new Node which has a high weight but a small RPT (because of the time). And it effects strong the Network. With a Softmax (Sigmoid) it would not effect strong the RPT of the rest, it would increase with time. 

Lets do some math:

RPT= Reputation Score
t= Time
K= Number of Nodes
b= Bias. The Bias i would do const. over all Nodes because otherwise it could decrese strongly the RPT in % of the other RNodes.

![RPT](https://user-images.githubusercontent.com/24302453/57968610-2de6b000-796d-11e9-91f3-5e760d2dd5cb.png)

**Comment by alex031029** [comment]
Viewing your comments in this page offers me deja vu that I was still in my lab and reviewing papers. I am glad that you offered such explicit analysis and even took consideration of time. If my guesstimate is right, you should be an expert in math or (and) machine learning. You seemingly not fond of discrete function, but all programs are in essence discrete. 

Your consideration of time looks sound and decent. This temporal model reminds of operation system scheduling, where process can increase its priority along with time. However, it is pretty hard to implement it on chain, since the info of t_l and t_k is hard to retrieve.

**Comment by alex031029** [comment]
Althought hard division is too rough, it guarantees that there are at least a proportion of proposers are from low RPT group. Except long-tail nodes, we are also concerning oligopoly where the odds of nodes with low rpts getting elected are practically negligible. 

You may consider it as upper house and lower house, or you can regard them as representatives from minority group.

**Comment by Mateus224** [comment]
of course all programs are discrete but the question is how fine is the division. Heheh math expert^^. Honestly I studied Systems Engineering with the specialization of robotics and automation and in my Master i specialized myself in control theory and I m writing now my master thesis and science paper in deep Reinforcement learning in the German Research Center for AI, where i additionally have a job in machine learning algorithms. But yeah thanks for the "expert" ^^. 

However why is t_l and t_k hard to retrieve? t_l and  t_k is the time in Blocks (I know time is not easy to get on a Blockchain but we need just the time in Blocks)

t_l= LastCreatedBlockFrom_L_Node  -  NewestBlock

why i dont like the hard devision i wrote in the first comment:

"Because if you make it with a hard division it could again happens that a few people e.g. from the low reputation pool will be not selected if the pool will be much bigger (hundrets of low RPT Nodes in the mainnet). Then you should again divided it...?"

Because then you have again in this pool again the same problem if the pool is getting bigger.
But when i will have time on weekend or so i will finally take a look into the code ^^

**Comment by alex031029** [comment]
The major reason I said it is hard to retrieve t_l is solidity language, which used for writing smart contract.
All parameters involved in election need to be written in smart contract. But solidity, despite that it is supposed to be turning complete, is much harder to use compared to golang or python. We hope this election smart contract as succinct as possible. 

In your temporal model, smart contract needs to retrospect the chain back to a certain block height until it finds t_i for all RNode i. And we wish to keep any solidity file simple and easy to debug.
