### ISSUE TITLE
Add impeach reason to CPC API

### ISSUE THREAD

**Issue by siebeneicher** [CPChain/chain#49]
Feature: show impeach reason in the CPC API.

The reason a block gets impeached is very interesting for all rnode providers, so we can actually see if our connection or cpu is not up to the task. Thus said, each one can individually improve his/her rnode machine/network which results in an overall more robust network.

**Comment by HKet** [comment]
I really think this is a useful add on. In my opinion it is the only way to get a good understanding of why an RNode has impeached blocks

**Comment by alex031029** [comment]
I second it. 

But this feature is not as easy as it seems in terms of implementation. To be honest, we can hardly figure out what the real reason is behind a certain impeached block. It is because the majority of impeachment appear in a exactly the same way, where 2/3 of timers of validators expire. 

This expiration can be caused by several scenarios, like connection error, long processing time (either low CPU computing power or large transaction list), incorrect local clock of proposer, undiscovered latent bugs, unexpected abort of validators, etc etc. We need some time to design a scheme analyzing these possible reasons. 

We, as developers, also demand this feature to help us debug code. I think we are going to have this feature in the future.
