### ISSUE TITLE
Calculation of proposerlist is not following RPT as expected

### ISSUE THREAD

**Issue by kbaf** [CPChain/chain#57]
Hi,

With these images i am trying to prove that the calculation of which nodes are elected to be in the commitee as proposer is not correct as it is now.

In my eyes, the higher the RPT of a node is, the higher the chances to be elected as a proposer.
Currently, the nodes with the highest RPT are not elected more than nodes with a lower RPT.

Here you can see that the RPT is higher as the balance (counts for 50%) is higher.

![image](https://user-images.githubusercontent.com/49679033/58454750-b6a8dd00-811f-11e9-901d-017aba4a1e8a.png)

And here you can see that a higher RPT not necessarily means that they create more blocks, this also counts for longer timeframes, but i choosed to display 12H TF now because some changes to the smart-contract has been made yesterday and i want to filter data before that.

![image](https://user-images.githubusercontent.com/49679033/58454825-f8398800-811f-11e9-84b1-2b96637bebfc.png)

And here you can see how the nodes with high balances are outperformed totally by the nodes with lower balances.

 
![image](https://user-images.githubusercontent.com/49679033/58455002-772ec080-8120-11e9-9bf1-8af435c69744.png)

**Comment by kbaf** [comment]
I have created a similar charts with the team nodes filtered, in the previous 3 charts the teamnodes are included.

![image](https://user-images.githubusercontent.com/49679033/58535014-1325fe00-81ed-11e9-8bf8-66d29843cbc6.png)

![image](https://user-images.githubusercontent.com/49679033/58535022-17eab200-81ed-11e9-9bed-ed3045b60c75.png)


![image](https://user-images.githubusercontent.com/49679033/58535046-1faa5680-81ed-11e9-94c5-016cc56fd674.png)


It looks like that, the higher the balance of a node, the less impact it has on the amount of blocks it creates.

Is this the behaviour that is wanted by cpchain?

**Comment by kbaf** [comment]
One addition to the last image, a red line which shows perfectly how the balances around 400/500K are competing in the same area with the higher balances.

![image](https://user-images.githubusercontent.com/49679033/58541813-9c90fc80-81fc-11e9-8226-d5d41b3da070.png)

**Comment by alex031029** [comment]
Good work! Many thanks for your kind support and spectacular chats showing the relationships.
I am still viewing these charts, but one question I can answer now is that the relatively low impact of balance. 

In RPT calculation, the ranking of balance is taken into consideration instead of absolute value. The top one holder with more than 2.4M tokens, only have very little advantage comparing to the 10th holder with merely 60k tokens. This methodology is also adopted in other dimension like transaction number. 

If you wish, you may make another plot whose x-axis is the ranking of balance instead of absolute value. I think this plot can have a nicer shape.
