### ISSUE TITLE
Smaller nodes outperforms nodes with higher balances

### ISSUE THREAD

**Issue by kbaf** [CPChain/chain#63]
Hi, 

When i look at this overviews of last 12H (after the update of 0.2.11) it is still true that the smaller nodes are generating more blocks in ratio to their balance than the bigger nodes.

It was said always that a node runner wouldn't gain anything by running more smaller nodes instead of a larger one with the same amount of CPC.

These analysis shows otherwise however. Smaller nodes perform better than bigger ones.

Below: Nodes sorted at performance ratio descending (blocks / balance ratio)

![image](https://user-images.githubusercontent.com/49679033/58756764-35768f00-84ff-11e9-8e69-26f7e47da34e.png)

Below: Nodes sorted at RPT descending

![image](https://user-images.githubusercontent.com/49679033/58756773-52ab5d80-84ff-11e9-8084-b1f84ad82fa7.png)

**Comment by kbaf** [comment]
And here nodes sorted by blocks descending (all screenshots are the latest 12H since update to 0.2.11)

![image](https://user-images.githubusercontent.com/49679033/58756800-b7ff4e80-84ff-11e9-83c8-e0e2d669146d.png)

**Comment by kbaf** [comment]
I have added the nodes with 0 blocks in a timeframe to the overview, by doing this, the performance ratios for the nodes are even less balanced.

![pr](https://user-images.githubusercontent.com/49679033/58758287-cc504500-8519-11e9-9876-187cbe8f4030.jpg)

**Comment by alex031029** [comment]
The figures you provide look pretty distorted just like you stated. 
![image](https://user-images.githubusercontent.com/2452221/58878392-bf904480-8705-11e9-92ce-8e3b22ae7bf9.png)
I screenshotted the histogram at the time I am typing the post, which looks slightly nicer. But it still contains a large amount of nodes with high balance while sealing no block. After I checked these addresses, I found all their recent transactions failed due to their out-dated version.
