### ISSUE TITLE
Do not advise to put password in a file with keystore file on same server

### ISSUE THREAD

**Issue by hvredevoort** [CPChain/chain#75]
I'm not happy with the way CPChain allows rnodes to run by a combination of a keystore file and a password.
CPChain recommends to use a password file to unlock the keystore file which is located in the keystore directory. 
Please find an acceptable solution for protecting the funds. The wallet should be offline or protected by a hardware device such as a Ledger.
This is just waiting for the first hack to happen!
The ./cpchain campaign command does not even work with a password file!!!!
This should be an interactive password as well, but rather look for a better solution.

**Comment by alex031029** [comment]
Hi there,

The reason we put the keystore file in the server is that a proposer needs it to generate the signatures and seal a block. As far as I know the other blockchain algorithms also require the keystore to be stored in the server. 

The Ledger requires you to manually press the button in order to sign a transaction, which is not suitable for an automatic process like mining. I appreciate if you have any feasible idea of handle your concern.

As for `./cpchain campaign`, the help manual indicates that you can use a password file. But I just found we didn't support keyboard input for the password for `./cpchain campaign`. An issue has been assigned to fix the problem. 

![image](https://user-images.githubusercontent.com/2452221/62589386-aff6cd00-b8fb-11e9-8f15-599bf32f60ce.png)

**Comment by hvredevoort** [comment]
Hi Alex, thanks for your answer and for initiating the fix for the password file requirement for cpchain campaign.
I agree that having to push a ledger button for each transaction is rather cumbersome if that is necessary for each block to be sealed. 
Perhaps you can start with allowing ledger and press the button when starting the cpchain run command.
Perhaps you can separate the wallet with the tokens from a wallet which receives the awards. A hack will only risk the wallet which receive the CPC from mining and use the Ledger or password only for transferring CPC from reward wallet to main wallet. Of course we would need to find a way to read the amount of CPC in the main wallet and transfer 200K for rnode operation.
Also talk to LTO Networks because I believe they use an offline wallet.
Thanks again for exchanging ideas for improving security.
Cheers, Hans

**Comment by alex031029** [comment]
Hi Hans,

Thanks for your quick response. 

Other people including industry nodes have asked me about a same question that if we can separate mining account and reward account to reduce the risk. We do not have a mechanism to implement it on our chain infrastructure, but you can do it by yourself by transferring tokens. 

I consulted my teammate in charge of Ledger development, he said Ledger does not provide methods to circumvent the press operation and the mainstream apps on Ledger all require the physical press on the cold wallet. 

With Regards,
Yanchen

**Comment by hvredevoort** [comment]
Yes I understand, but I only mean the time when the ./cpchain run command is run
So press the button only for starting the rnode or requesting ./cpchain campaign 
This would keep your private key and your wallet safe.
