### ISSUE TITLE
Rnode shuts down after proposing a couple hours

### ISSUE THREAD

**Issue by martijnvdweerdt** [CPChain/chain#80]
**Where does the bug occur?**
Chain

**What is your wallet address and your balance?**
If it is too private to answer, you can skip it. 

**Describe the bug**
After setting up the Rnode, it syncs and succesfully starts to participate in the network. However, two errors occur. 1. After a couple of hours of running, the node shuts down and stops. The corresponding error message is  'packet_write_wait: connection to VPS port xxxx: Broken pipe'. 
2. Also, sometimes a transactions fails (see printscreen below). 

**To Reproduce**
To reproduce the behavior, I just have to restart the node again and after a couple hours of running and proposing blocks, it shows the same behavior. 

**Expected behavior**
Not sure honestly. What I noticed the first time, though, was that the VM on my computer that I used for setting up the node, stopped running. After changing its configuration, the VM did not stop anymore. However, the Rnode itself shuts down with the error message as shown above.
What is noticeable also

**Screenshots**
![image](https://user-images.githubusercontent.com/54245216/63228121-4de97200-c1ef-11e9-8de0-00d4d12165b5.png) This is the printscreen of one of the error transactions (problem 2). 

** Configuration (please complete the following information):**
 - OS: Windows 10
 -  VM: Ubuntu 18.04
 - cpchain version [e.g. 0.2.3]

**Additional context**
If your bug can only be reproduced occasionally, please emphasize it.

**Comment by alex031029** [comment]
Hi there. Thanks for your report.

`packet_write_wait: connection to VPS port xxxx: Broken pipe` is not a CPChain error message. My speculation is that the break of SSH session. Here is a link discussing similar error code https://askubuntu.com/questions/127369/how-to-prevent-write-failed-broken-pipe-on-ssh-connection

To prevent this problem, you may use command `nohup`, or applications like "tmux", "systemd", "start-stop-daemon".

**Comment by alex031029** [comment]
Hi there. Thanks for your report.

`packet_write_wait: connection to VPS port xxxx: Broken pipe` is not a CPChain error message. My speculation is that the break of SSH session. Here is a link discussing similar error code https://askubuntu.com/questions/127369/how-to-prevent-write-failed-broken-pipe-on-ssh-connection

To prevent this problem, you may use command `nohup`, or applications like "tmux", "systemd", "start-stop-daemon".

**Comment by alex031029** [comment]
As for the failed transaction. It is not caused by your operation.
Although many reasons may incur this failure, the primary one is the insufficient gas.

As you may know, each campaign claim is a transaction of 0 value. But it still needs gas as transaction fee. A function `estimateGas` is invoked to, as referred by the name, to estimate the gas for this transaction. And you node is going to pay the gas of this estimation.

But the real gas need to pay is always changing. If the estimation is below the actual value you are required to pay, an error of insufficient gas happens and results in a failed transaction.

You do not need to worry about it, it is simply a matter of probability. Usually the estimation is correct, and the odds of failed transaction of claiming campaign are relatively low.
