### ISSUE TITLE
Problems after upgrading to 0.4.8

### ISSUE THREAD

**Issue by hvredevoort** [CPChain/chain#92]
I added a new bug report because of update to 0.4.8 but the previous report shows similar errors

**Where does the bug occur?**
chain

**What is your wallet address and your balance?**
If it is too private to answer, you can skip it. 

**Describe the bug**
Since update to 0.4.8 I see more sync errors, sync shutting down, broken pipe erros

**To Reproduce**
Update 0.4.6 to 0.4.8

**Expected behavior**
no sync errors

**Screenshots**
![Update 0 4 8](https://user-images.githubusercontent.com/6986026/66798029-e9b90500-ef36-11e9-8e7c-3e4f9de3e9ca.png)

** Configuration (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - cpchain version [e.g. 0.2.3]
Ubuntu 19.04
CPChain 0.4.8

**Additional context**
If your bug can only be reproduced occasionally, please emphasize it.

**Comment by hvredevoort** [comment]
Address: 0x42204cC9F4f188A21e90403DC8D21A3F1957dDBd and
0x5019A330Ab801A366A6960Ff960fB1a72031b96b
I also got an impeached block on the first RNode

**Comment by hvredevoort** [comment]
I downgraded to 0.4.6 because I got too many errors and no sealed blocks

**Comment by alex031029** [comment]
The screenshot indicates that the peer your node trying to sync disconnected. Since the `cpchain` was running in multithreading, many same warnings can pop up in a short time. But all these warning should not bother you from sealing blocks. 

We have tested the 0.4.8 version in our pre-production environment, which did not have anything wrong with sealing process. So currently I have no idea why your node cannot seal any blocks running the newest version. 

I will keep you updated.

**Comment by hvredevoort** [comment]
I reinstalled 0.4.8, did a compact of the database and was able to start again
Just sealed some blocks, so this node is fine now
